services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    entrypoint: ["/bin/bash", "/start.sh"]
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./start.sh:/start.sh:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama:
